### ISSUE TITLE
Python, pushd error

### ISSUE THREAD

**Issue by salusasecundos** [FreddieChopin/bleeding-edge-toolchain#29] opened 2023-03-27 05:39 UTC
checking whether to use python... yes
checking for python... /usr/bin/python
  CC       libctf_la-ctf-open.lo
  CC       libctf_la-ctf-serialize.lo
checking for python... no
configure: error: python is missing or unusable
  CC       libctf_la-ctf-sha1.lo
make[1]: *** [Makefile:11124: configure-gdb] Error 1
make[1]: *** Waiting for unfinished jobs....

Does anybody know how to solve that, can anybody help?
Python is installed and previous versions compiled good.
That was the script changed by me.

Current script works as follows 

********** Resuming last build
********** Download
********** Extract
---------- Patching gdb-12.1
./build-bleeding-edge-toolchain.sh: 813: pushd: not found
miha@ksonasu:~/allaccess/Gcc-12_t$

how to solve that?

System is Ubuntu 20.

**Comment by salusasecundos** [comment] 2023-04-07 23:59
Fixed, in system i choose 
update-alternatives --install /usr/bin/python python /usr/bin/python3.10 2
update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
update-alternatives --install /usr/bin/python python /usr/bin/python3 3

update-alternatives --config python
-------------------------------------------
for GDB 13.1 I choose Python 
pythonVersion="3.3.5"

I assembled version arm-none-eabi-gcc-13-20230319-230404-win64

everything works for now.

There will be a problem with sym-mingw32.o command to create it somehow doesn't work, so i went to directory with sym-mingw32.cc file, executed command there and get .o file. then hit --resume and I copied that file to build directory with GCC and file was found. Whole compilation were successful.

my versions

binutilsVersion="2.40"
expatVersion="2.5.0"
gccVersion="13-20230319"
gdbVersion="13.1"
gmpVersion="6.2.1"
islVersion="0.25"
libiconvVersion="1.17"
mpcVersion="1.3.1"
mpfrVersion="4.2.0"
newlibVersion="4.3.0.20230120"
pythonVersion="3.3.5"
zlibVersion="1.2.13"

**Comment by FreddieChopin** [comment] 2023-04-08 09:33
So you basically updated most of the "core" stuff (gcc, gdb, binutils and newlib), also updating python for the windows version from v2 to v3 and it works? Nice (; Last time I tried GCC for windows would not like python v3 and explicitly required python v2 /;

I guess gcc 13 will be released soon, so I will probably update the script soon as well.

The first error that you saw - that `pushd: not found` - is caused by your system not having `pushd` command. You need to find the package that has it and install it. It seems that in ArchLinux `pushd` and `popd` are just bash built-ins, but I may be wrong here.

**Comment by salusasecundos** [comment] 2023-04-12 01:22
Yeah updated everything and yes python for windows version is 3.3.5, version 2.17 is not accepted at all
I thought that I'm doing something wrong with python bit no. Python version should be updated as well as linux one.
There only one problem that i found is sys_mingw32.o doesn't want to be created by command

x86_64-w64-mingw32-g++  -fno-PIE -c /home/miha/WORK/GCC-13/sources/gcc-13-20230319/gcc/config/i386/sym-mingw32.cc sym-mingw32.o

x86_64-w64-mingw32-g++: error: sym-mingw32.o: No such file or directory


So what i did is: I get to folder with sources /home/.../WORK/GCC-13/sources/gcc-13-20230319/gcc/config/i386/ fnd executed that command right there and i got that sym-mingw32.o file. Then i continued compiling and the same time copied this file to build directory and the file hooked up, so that's the only problem.

Other problems i solved more or less easily. You can try with my versions to see what problemms can appear to fix them in script if it is script problem.

**Comment by dobryj** [comment] 2023-05-12 12:55
pushd error is caused by using of /bin/sh where is not pushd supported. It is bash extension. Therefore when sh is link to bash, it works. With real sh not.
Solution is change /bin/sh to /bin/bash on the first line or start bash with script as input.

**Closed as completed** 2024-04-05 07:41 UTC
